-- CreateTable
CREATE TABLE `invoices` (
    `id` VARCHAR(191) NOT NULL,
    `uuid` VARCHAR(50) NOT NULL,
    `emisorNombre` VARCHAR(255) NOT NULL,
    `emisorRfc` VARCHAR(20) NOT NULL,
    `receptorNombre` VARCHAR(255) NOT NULL,
    `receptorRfc` VARCHAR(20) NOT NULL,
    `total` DECIMAL(15, 2) NOT NULL,
    `subtotal` DECIMAL(15, 2) NULL,
    `iva` DECIMAL(15, 2) NULL,
    `moneda` VARCHAR(10) NOT NULL,
    `tipo_cambio` DECIMAL(10, 4) NULL,
    `fecha` DATE NOT NULL,
    `fecha_timbrado` DATETIME(3) NULL,
    `folio` VARCHAR(50) NULL,
    `serie` VARCHAR(25) NULL,
    `metodo_pago` VARCHAR(50) NULL,
    `forma_pago` VARCHAR(50) NULL,
    `uso_cfdi` VARCHAR(10) NULL,
    `tipo_comprobante` VARCHAR(10) NULL,
    `estado` VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    `fecha_programada` DATE NULL,
    `fecha_pago` DATE NULL,
    `referencia_pago` VARCHAR(100) NULL,
    `observaciones` TEXT NULL,
    `xml_content` LONGTEXT NULL,
    `pdf_url` VARCHAR(500) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    `uploaded_by` VARCHAR(100) NULL,

    UNIQUE INDEX `invoices_uuid_key`(`uuid`),
    INDEX `invoices_uuid_idx`(`uuid`),
    INDEX `invoices_emisorRfc_idx`(`emisorRfc`),
    INDEX `invoices_receptorRfc_idx`(`receptorRfc`),
    INDEX `invoices_estado_idx`(`estado`),
    INDEX `invoices_fecha_idx`(`fecha`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
