-- CreateTable
CREATE TABLE `clients` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` TEXT NULL,
    `birthday` DATETIME(3) NULL,
    `email` VARCHAR(255) NULL,
    `address` TEXT NULL,
    `birthplace` TEXT NULL,
    `curp` VARCHAR(255) NULL,
    `elector_key` TEXT NULL,
    `mobile` TEXT NULL,
    `phone` TEXT NULL,
    `f_lastname` TEXT NULL,
    `m_lastname` TEXT NULL,
    `state` TEXT NULL,
    `marital_status` INTEGER NULL,
    `marital_registry` INTEGER NULL,
    `street` TEXT NULL,
    `interior_number` TEXT NULL,
    `external_number` TEXT NULL,
    `suburb` TEXT NULL,
    `postal_code` TEXT NULL,
    `municipality` TEXT NULL,
    `near` TEXT NULL,
    `company_name` TEXT NULL,
    `company_street` TEXT NULL,
    `company_external_number` TEXT NULL,
    `company_interior_number` TEXT NULL,
    `company_suburb` TEXT NULL,
    `company_postal_code` TEXT NULL,
    `company_phone` TEXT NULL,
    `company_municipality` TEXT NULL,
    `company_state` TEXT NULL,
    `company_near` TEXT NULL,
    `company_mobile` TEXT NULL,
    `job` TEXT NULL,
    `antiquity` TEXT NULL,
    `monthly_income` BIGINT NULL,
    `additional_income` BIGINT NULL,
    `fixed_costs` INTEGER NULL,
    `bank` TEXT NULL,
    `gender` TEXT NULL,
    `affiliation_number` TEXT NULL,
    `rfc` TEXT NULL,
    `is_rented` TEXT NULL,
    `time_rented` TEXT NULL,
    `monthly_rent` INTEGER NULL,
    `birth_state` TEXT NULL,
    `is_foreign` BOOLEAN NULL,
    `created_by` INTEGER NULL,
    `work_foreign` BOOLEAN NULL,
    `company_rfc` TEXT NULL,
    `business_name` TEXT NULL,
    `adquisition` TEXT NULL,
    `company_bussiness` TEXT NULL,
    `marital_regimen` INTEGER NULL,
    `working_time_start` TIME NULL,
    `working_time_end` TIME NULL,
    `location` TEXT NULL,
    `credit` TEXT NULL,
    `credit_type` TEXT NULL,
    `passport` TEXT NULL,
    `ine_number` TEXT NULL,
    `user` INTEGER NULL,
    `created_at` DATETIME(3) NULL,
    `updated_at` DATETIME(3) NULL,
    `company_business` VARCHAR(255) NULL,
    `beneficiary` INTEGER NULL,
    `completion_date` DATETIME(3) NULL,
    `client_status` INTEGER NULL,
    `idmex` VARCHAR(255) NULL,
    `whatsapp_number_id` VARCHAR(255) NULL,
    `whatsapp_recipient_number` VARCHAR(255) NULL,
    `messenger_conversation_id` VARCHAR(255) NULL,
    `messenger_recipient_id` VARCHAR(255) NULL,
    `campaing` INTEGER NULL,
    `external_id` VARCHAR(255) NULL,
    `campaign_form_date` DATETIME(3) NULL,
    `instagram_id` VARCHAR(255) NULL,
    `last_contact` DATETIME(3) NULL,
    `change_phase_date` DATETIME(3) NULL,
    `last_phipeline_phase` VARCHAR(255) NULL,
    `assigned_at` DATETIME(3) NULL,
    `move_phase_by` INTEGER NULL,
    `nationality` VARCHAR(255) NULL,

    INDEX `clients_email_idx`(`email`),
    INDEX `clients_curp_idx`(`curp`),
    INDEX `clients_created_at_idx`(`created_at`),
    INDEX `clients_updated_at_idx`(`updated_at`),
    INDEX `clients_client_status_idx`(`client_status`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
